version: '3'
services:

  app:
      image: kittenplanet/kp_admin
      container_name: kp_app
      restart: always
      # working_dir: ~/Desktop/docker-test/admin_server/app
      # ports:
      #   - 8080:8080
      # volumes:
      #   - ~/Desktop/docker-test/admin_server/app/tmp:/app
      expose:
        - "8080"

  nginx:
    image: nginx:1.14
    container_name: kp_nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/services/homes/jykim/docker/admin_server/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

    
